# To change this template, choose Tools | Templates
# This dummy file should be overwritten by {datapath}/config/choffice.properties in the file system
db.url=jdbc:mariadb://localhost/choffice
db.user=dbUser
db.password=dbPassWd
jaas.password=Password_to_test_jaas
mongodb.connectString=mongodb://user:pwd@localhost/?authSource=admin
mongodb.db=db